### ISSUE TITLE
negative bndbox values are loaded as string

### ISSUE THREAD

**Issue by Blubberblub** [Alek-dr/PascalVOC#2]
When loading annotations from xml with the annotation_from_xml function the library loads negative bndbox values as type. This seems wrong and causes issues when using other functions like draw_boxes.

The xml shouldn't have negative values but it happens with some labeling tools. In my case i used https://www.makesense.ai/

Example voc_xml:

```
<annotation>
	<folder>my-project-name</folder>
	<filename>test.jpg</filename>
	<path>/my-project-name/test.jpg</path>
	<source>
		<database>Unspecified</database>
	</source>
	<size>
		<width>355</width>
		<height>539</height>
		<depth>3</depth>
	</size>
	<object>
		<name>cat1</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>-2</xmin>
			<ymin>-3</ymin>
			<xmax>355</xmax>
			<ymax>333</ymax>
		</bndbox>
	</object>
	<object>
		<name>cat1</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>230</xmin>
			<ymin>441</ymin>
			<xmax>336</xmax>
			<ymax>525</ymax>
		</bndbox>
	</object>
</annotation>
```

**Comment by Alek-dr** [comment]
@Blubberblub thanks for catching that bug. Please, update package version. Now there is the parameter clip_zero
`
 ann = annotation_from_xml("example.xml", clip_zero=True)
`
If clip_zero equals "True" all negative values will clip to zero. True is default value. Also I added check for type to prevent str fields.
